### ISSUE TITLE
Remove unused folders and wizard-generated introduction readme files

### ISSUE THREAD

**Issue by ghost** [biohazard999/fixing-an-n-plus-1-perf-problem-in-xaf-xpo#1]
When looking at an XAF example repo ideally it should be cleaned to have only the files related to the example. The DevExpress XAF VS templates generates a lot of readmes in often unused folders for example: https://github.com/biohazard999/fixing-an-n-plus-1-perf-problem-in-xaf-xpo/tree/master/fixing-an-n-plus-1-perf-problem-in-xaf-xpo/fixing_an_n_plus_1_perf_problem_in_xaf_xpo.Module.Win/Controllers

**Comment by biohazard999** [comment]
I finally should do a *clean* repro template.

**Comment by biohazard999** [comment]
Should be done
